# Generated by Django 3.1.7 on 2021-04-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dukaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Mal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('photo_link', models.CharField(blank=True, max_length=200, null=True)),
                ('selling_price', models.CharField(blank=True, max_length=20, null=True)),
                ('active_status', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('dukaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mal_dukaan', to='dukaandaar_app.dukaan')),
                ('tags', models.ManyToManyField(blank=True, db_column='tag', null=True, related_name='mal_tag', to='dukaandaar_app.Tag')),
            ],
            options={
                'verbose_name': 'Mal',
                'verbose_name_plural': 'mals',
            },
        ),
    ]
