# Generated by Django 3.1.1 on 2021-04-06 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dukaandaar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukaan',
            name='user',
            field=models.ForeignKey(db_column='auth_user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kagibase_user', to='auth.user'),
            preserve_default=False,
        ),
    ]
