# Generated by Django 3.1.1 on 2021-04-06 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dukaandaar_app', '0002_dukaan_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dukaan',
            old_name='user',
            new_name='dukaan_id',
        ),
    ]
