# Generated by Django 3.1.7 on 2021-04-06 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dukaandaar_app', '0003_auto_20210406_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dukaan',
            old_name='name',
            new_name='dukaan_name',
        ),
        migrations.AlterField(
            model_name='dukaan',
            name='dukaan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
