# Generated by Django 3.1.7 on 2021-04-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaandaar_app', '0004_auto_20210406_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='dukaan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='dukaan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
