# Generated by Django 3.1.7 on 2021-04-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaandaar_app', '0006_dukaan_active_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mal',
            name='active_status',
        ),
        migrations.AlterField(
            model_name='mal',
            name='name',
            field=models.CharField(max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mal',
            name='quantity',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
    ]
